#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# hello_page:
#   path: /hehe/
#   controller: Symfony/Boundle/FrameworkBoundle/Controller/TemplateController::templateAction
#   defaults:
#     template: 'hello_page.html.twig'