<?php

namespace ContainerNXkA7IJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Services\Notification' shared autowired service.
     *
     * @return \App\Services\Notification
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'Notification.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'FileUploader.php';

        return $container->privates['App\\Services\\Notification'] = new \App\Services\Notification('admin@admin.com', ($container->privates['App\\Services\\FileUploader'] ?? ($container->privates['App\\Services\\FileUploader'] = new \App\Services\FileUploader($container))));
    }
}
