<?php

namespace ContainerBSx6iDr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B3_DSSIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B3.dSSI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.B3.dSSI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploader' => ['privates', 'App\\Services\\FileUploader', 'getFileUploaderService', true],
            'notification' => ['privates', 'App\\Services\\Notification', 'getNotificationService', true],
        ], [
            'fileUploader' => 'App\\Services\\FileUploader',
            'notification' => 'App\\Services\\Notification',
        ]);
    }
}
