<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNXkA7IJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNXkA7IJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNXkA7IJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNXkA7IJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNXkA7IJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'NXkA7IJ',
    'container.build_id' => '3eaa6f4b',
    'container.build_time' => 1608473159,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNXkA7IJ');
